excluded:
  - .build
  - Brewy.xcodeproj

opt_in_rules:
  - closure_body_length
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - yoda_condition

disabled_rules:
  - todo
  - opening_brace

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 600
  error: 800

type_body_length:
  warning: 500
  error: 700

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 3
  function_level: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

closure_body_length:
  warning: 50
  error: 70

large_tuple:
  warning: 4
  error: 5
